name: Version Bump
on:
  push:
    branches:
      - master

jobs:

  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Setup GIT
        run: |
          git switch -c master
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"

      - name: Update & Push
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          printf "\n\n$(date)" >> README.md
          git add .
          git commit -m "GitHub action test."
          git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY"
